package us.smt.turizm.domen.model

import us.smt.turizm.R
import java.io.Serializable

data class PlaceDetails(
    var id: String="",
    val name: String,
    val address: String,
    val about: String,
    val isCanBron: Boolean,
    val service: String,
    val distance: Double,
    val image: Int,
    val imageLink: String?,
    val isFavourite: Boolean,
    val long: Double?,
    val lat: Double?,
    val rating: Double?
):Serializable

fun getRandImage(): Int {
    val ls = listOf(
        R.drawable.toraja,
        R.drawable.meru,
        R.drawable.pink,
        R.drawable.bromo,
        R.drawable.rinjani,
        R.drawable.rinjani_1,
        R.drawable.rinjani_2,
        R.drawable.rinjani_3,
        R.drawable.rinjani_4
    )
    return ls.shuffled().first()
}

fun getAllData(): List<PlaceDetails> {
    val ls = ArrayList(ancientPlaces)
    ls.addAll(additionalAncientPlaces)
    ls.addAll(parks)
    ls.addAll(hotels)
    ls.addAll(restaurants)
    ls.addAll(cafesAndFastFoods)
    return ls
}

val ancientPlaces = listOf(
    PlaceDetails(
        name = "Registan",
        address = "Samarkand, Uzbekistan",
        about = "A historic center of Samarkand, renowned for its stunning Islamic architecture and vibrant square.",
        isCanBron = false,
        service = "Sightseeing",
        distance = 2.5,
        image = getRandImage(),
        imageLink = "https://www.advantour.com/img/uzbekistan/samarkand/registan.jpg",
        isFavourite = false,
        long = 39.6544,
        lat = 66.9757,
        rating = 4.9
    ),
    PlaceDetails(
        name = "Itchan Kala",
        address = "Khiva, Uzbekistan",
        about = "A UNESCO World Heritage site featuring ancient mosques, madrasas, and towering minarets.",
        isCanBron = false,
        service = "Heritage Site",
        distance = 1.0,
        image = getRandImage(),
        imageLink = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgxEwszOgZkkpdZ62SAVBX72crtEJZ7NO_Ow&s",
        isFavourite = true,
        long = 41.3775,
        lat = 60.3590,
        rating = 4.8
    ),
    PlaceDetails(
        name = "Shah-i-Zinda",
        address = "Samarkand, Uzbekistan",
        about = "A famous necropolis in Samarkand, known for its intricate tilework and historical significance.",
        isCanBron = false,
        service = "Cultural Site",
        distance = 3.1,
        image = getRandImage(),
        imageLink = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdWGDnxWX9EVfB3OFi5JgOjMKf2IJIBv-2_g&s",
        isFavourite = true,
        long = 39.6720,
        lat = 66.9729,
        rating = 4.7
    ),
    PlaceDetails(
        name = "Ark of Bukhara",
        address = "Bukhara, Uzbekistan",
        about = "An ancient fortress in Bukhara, once a residence of the Emir and a symbol of power.",
        isCanBron = false,
        service = "Historical Fortress",
        distance = 4.2,
        image = getRandImage(),
        imageLink = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTs9O1ITta1pajxp0b2L0EObuc0WmI6ZOR9kQ&s",
        isFavourite = false,
        long = 39.7758,
        lat = 64.4158,
        rating = 4.6
    ),
    PlaceDetails(
        name = "Bibi-Khanym Mosque",
        address = "Samarkand, Uzbekistan",
        about = "A grand mosque built by Timur, featuring impressive domes and stunning architecture.",
        isCanBron = false,
        service = "Religious Site",
        distance = 2.0,
        image = getRandImage(),
        imageLink = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOf7LPkgprE5bewcpcQGABl_9ZZapWQeJkDA&s",
        isFavourite = true,
        long = 39.6638,
        lat = 66.9740,
        rating = 4.8
    ),
    PlaceDetails(
        name = "Kalyan Minaret",
        address = "Bukhara, Uzbekistan",
        about = "A towering minaret in Bukhara, also known as the 'Tower of Death' for its historic use.",
        isCanBron = false,
        service = "Historical Landmark",
        distance = 3.5,
        image = getRandImage(),
        imageLink = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0Fm-9S1dr5RViXxy__rUGLF87r_BcR2jgkA&s",
        isFavourite = false,
        long = 39.7749,
        lat = 64.4287,
        rating = 4.7
    ),
    PlaceDetails(
        name = "Chor Minor",
        address = "Bukhara, Uzbekistan",
        about = "A charming, four-towered building that once served as a gatehouse for a madrasa.",
        isCanBron = false,
        service = "Cultural Site",
        distance = 1.8,
        image = getRandImage(),
        imageLink = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUigGS6FKt_YdpkzeVcaUZY2PJdEhZh0fEgA&s",
        isFavourite = true,
        long = 39.7777,
        lat = 64.4263,
        rating = 4.6
    ),
    PlaceDetails(
        name = "Sitorai Mohi Hosa",
        address = "Bukhara, Uzbekistan",
        about = "A beautiful summer palace of the last Emir of Bukhara, blending European and Eastern styles.",
        isCanBron = false,
        service = "Palace",
        distance = 4.8,
        image = getRandImage(),
        imageLink = "https://www.tourstouzbekistan.com/uploads/news/my_files/uzbek%20culture/%D1%81%D0%B8%D1%82%D0%BE%D0%B0%20%D0%B8%20%D0%BC%D0%BE%D1%85%D0%B8%20%D1%85%D0%BE%D1%81%D0%B0.jpeg",
        isFavourite = false,
        long = 39.7983,
        lat = 64.4708,
        rating = 4.5
    ),
    PlaceDetails(
        name = "Lyabi-Hauz",
        address = "Bukhara, Uzbekistan",
        about = "A tranquil square with a historic pool surrounded by madrasas and teahouses.",
        isCanBron = false,
        service = "Cultural Area",
        distance = 0.7,
        image = getRandImage(),
        imageLink = "https://cdn.elebase.io/173fe953-8a63-4a8a-8ca3_root_ide_package_.us.smt.turizm.domen.model.getRandImage()bacb56d78a5/c3bdc5bd-8a7e-4912-bb36-df4b8142c98e-shutterstock_744206089.jpg?q=75",
        isFavourite = true,
        long = 39.7743,
        lat = 64.4217,
        rating = 4.8
    ),
    PlaceDetails(
        name = "Nurata Fortress",
        address = "Nurata, Uzbekistan",
        about = "An ancient fortress believed to have been founded by Alexander the Great.",
        isCanBron = false,
        service = "Historical Site",
        distance = 5.0,
        image = getRandImage(),
        imageLink = "https://central-asia.guide/wp-content/uploads/2021/06/nurota_fortress._root_ide_package_.us.smt.turizm.domen.model.getRandImage()024x682.jpg",
        isFavourite = false,
        long = 40.5602,
        lat = 65.6886,
        rating = 4.4
    ),
)
val additionalAncientPlaces = listOf(
    PlaceDetails(
        name = "Afrosiyob",
        address = "Samarkand, Uzbekistan",
        about = "An ancient site of Samarkand with ruins dating back to the 6th century BC.",
        isCanBron = false,
        service = "Archaeological Site",
        distance = 3.7,
        image = getRandImage(),
        imageLink = "https://www.samarkandtour.com/media/photos/Afrosiab_reconstruction.jpg",
        isFavourite = true,
        long = 39.7031,
        lat = 66.9738,
        rating = 4.6
    ),
    PlaceDetails(
        name = "Kyzylkum Desert Fortresses",
        address = "Karakalpakstan, Uzbekistan",
        about = "A series of ancient fortresses scattered across the Kyzylkum desert, showcasing historical defense structures.",
        isCanBron = false,
        service = "Cultural Landmark",
        distance = 6.5,
        image = getRandImage(),
        imageLink = "https://c8.alamy.com/comp/2C3M8YK/kyzyl-kala-fortress-ancient-khorezm-in-the-kyzylkum-desert-uzbekistan-2C3M8YK.jpg",
        isFavourite = false,
        long = 42.8000,
        lat = 60.7167,
        rating = 4.7
    ),
    PlaceDetails(
        name = "Termez Archaeological Museum",
        address = "Termez, Uzbekistan",
        about = "A museum and archaeological site displaying relics from ancient Buddhist and Islamic eras.",
        isCanBron = false,
        service = "Museum",
        distance = 2.2,
        image = getRandImage(),
        imageLink = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRX4m-xZu5XmUkbFfaSUx2MSjvmgQBaO74fCg&s",
        isFavourite = false,
        long = 37.2244,
        lat = 67.2780,
        rating = 4.5
    ),
    PlaceDetails(
        name = "Shakhrisabz Historic Center",
        address = "Shakhrisabz, Uzbekistan",
        about = "The birthplace of Amir Timur, known for the Ak-Saray Palace and other Timurid architecture.",
        isCanBron = false,
        service = "Cultural Site",
        distance = 4.0,
        image = getRandImage(),
        imageLink = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6whW-HL_aRPn_DyBg7Xh-rFxRNFc7oADP9Q&s",
        isFavourite = true,
        long = 39.0510,
        lat = 66.8340,
        rating = 4.8
    ),
    PlaceDetails(
        name = "Kok-Gumbaz Mosque",
        address = "Shakhrisabz, Uzbekistan",
        about = "A stunning mosque built during the Timurid dynasty, known for its blue domes.",
        isCanBron = false,
        service = "Religious Site",
        distance = 3.5,
        image = getRandImage(),
        imageLink = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSN8IVnV20g-9ANbNtLl-L2fD_f7Ah8X6TgA&s",
        isFavourite = false,
        long = 39.0499,
        lat = 66.8345,
        rating = 4.6
    ),
    PlaceDetails(
        name = "Kanka Ancient Settlement",
        address = "Tashkent Region, Uzbekistan",
        about = "An ancient Silk Road settlement with fascinating archaeological remains.",
        isCanBron = false,
        service = "Archaeological Site",
        distance = 7.8,
        image = getRandImage(),
        imageLink = "https://meros.uz/upload/2017/02/f658b8cab36a5d764eb964d9d3a23d0e-large.jpg",
        isFavourite = false,
        long = 41.3123,
        lat = 69.2494,
        rating = 4.4
    ),
    PlaceDetails(
        name = "Ming-Uruk Fortress",
        address = "Tashkent Region, Uzbekistan",
        about = "An ancient fortress showcasing the historical roots of the region's early civilizations.",
        isCanBron = false,
        service = "Historical Landmark",
        distance = 6.0,
        image = getRandImage(),
        imageLink = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQu36v7wPjSG4dvCRTAVNLoxE7yIhR4sNkYfg&s",
        isFavourite = false,
        long = 41.2901,
        lat = 69.2667,
        rating = 4.5
    ),
    PlaceDetails(
        name = "Surkhan Reserve",
        address = "Surkhandarya, Uzbekistan",
        about = "A natural and historical reserve featuring ancient petroglyphs and stunning landscapes.",
        isCanBron = false,
        service = "Cultural and Natural Reserve",
        distance = 8.3,
        image = getRandImage(),
        imageLink = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQW5o0GwEatZ_6Qte8GC0b81iaXsUQbbF1GDw&s",
        isFavourite = true,
        long = 37.7500,
        lat = 67.5000,
        rating = 4.6
    ),
    PlaceDetails(
        name = "Nurata Water Supply System",
        address = "Nurata, Uzbekistan",
        about = "An ancient underground water supply system built during Alexander the Great's time.",
        isCanBron = false,
        service = "Historical Site",
        distance = 2.1,
        image = getRandImage(),
        imageLink = "https://abc-tourism.uz/storage/Nurata/chashma%20complex.jpg",
        isFavourite = true,
        long = 40.5645,
        lat = 65.6897,
        rating = 4.7
    ),
    PlaceDetails(
        name = "Ayaz-Kala Fortress",
        address = "Karakalpakstan, Uzbekistan",
        about = "A well-preserved fortress offering stunning views of the surrounding Kyzylkum desert.",
        isCanBron = false,
        service = "Archaeological Site",
        distance = 5.9,
        image = getRandImage(),
        imageLink = "https://www.wmf.org/sites/default/files/styles/project_gallery_full_size/public/projects/gallery/S8220_1.jpg?itok=1LRJbT7c",
        isFavourite = true,
        long = 42.5306,
        lat = 61.3856,
        rating = 4.9
    )
)
val parks = listOf(
    PlaceDetails(
        name = "Central Park of Tashkent",
        address = "Tashkent, Uzbekistan",
        about = "A popular park in the heart of Tashkent, featuring walking paths, fountains, and recreational areas.",
        isCanBron = true,
        service = "Recreational Activities, Cafes",
        distance = 1.5,
        image = getRandImage(),
        imageLink = "https://uzbekistan.travel/storage/app/media/nargiza/cropped-images/central%20park-0-0-0-0_root_ide_package_.us.smt.turizm.domen.model.getRandImage()588756986.jpg",
        isFavourite = true,
        long = 41.3111,
        lat = 69.2797,
        rating = 4.7
    ),
    PlaceDetails(
        name = "National Park of Uzbekistan",
        address = "Tashkent, Uzbekistan",
        about = "A vast park with lush greenery, lakes, and areas for picnics and sports.",
        isCanBron = true,
        service = "Nature Walks, Boat Rentals",
        distance = 3.0,
        image = getRandImage(),
        imageLink = "https://people-travels.com/storage/images/Tashkent%20parks/National-park-after-Alisher-Navoi.jpg",
        isFavourite = false,
        long = 41.2950,
        lat = 69.2862,
        rating = 4.8
    ),
    PlaceDetails(
        name = "Navoi Park",
        address = "Tashkent, Uzbekistan",
        about = "A historic park named after Alisher Navoi, featuring statues and a scenic lake.",
        isCanBron = false,
        service = "Sightseeing, Relaxation",
        distance = 2.0,
        image = getRandImage(),
        imageLink = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiYPSzQd24BqX_XT7ncZXuOermdOCgj0kRBg&s",
        isFavourite = true,
        long = 41.3143,
        lat = 69.2652,
        rating = 4.6
    ),
    PlaceDetails(
        name = "Anhor Lokomotiv Park",
        address = "Tashkent, Uzbekistan",
        about = "An amusement park with thrilling rides, a water park, and family-friendly attractions.",
        isCanBron = true,
        service = "Amusement Rides, Food Stalls",
        distance = 4.5,
        image = getRandImage(),
        imageLink = "https://people-travels.com/storage/images/WMMmAg9Vx825Bs9TbEqfN6SMqXQRSuQ3hvpdZXQN.jpg",
        isFavourite = true,
        long = 41.3280,
        lat = 69.2916,
        rating = 4.7
    ),
    PlaceDetails(
        name = "Ashgabat Park",
        address = "Tashkent, Uzbekistan",
        about = "A charming park inspired by Turkmenistan's Ashgabat, with unique sculptures and architecture.",
        isCanBron = false,
        service = "Photo Spots, Relaxation",
        distance = 2.3,
        image = getRandImage(),
        imageLink = "https://people-travels.com/storage/images/Tashkent%20parks/Ashkhabad-Park-in-Tashkent.jpg",
        isFavourite = false,
        long = 41.3152,
        lat = 69.2900,
        rating = 4.5
    ),
    PlaceDetails(
        name = "Botanical Garden of Tashkent",
        address = "Tashkent, Uzbekistan",
        about = "A serene garden showcasing a variety of plants and flowers, perfect for nature enthusiasts.",
        isCanBron = false,
        service = "Nature Walks, Guided Tours",
        distance = 5.0,
        image = getRandImage(),
        imageLink = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPT4KnJMOoYcAS5A800fharzYzn0lu4H76Bg&s",
        isFavourite = true,
        long = 41.3481,
        lat = 69.2840,
        rating = 4.9
    ),
    PlaceDetails(
        name = "Ecopark",
        address = "Tashkent, Uzbekistan",
        about = "An eco-friendly park with bike paths, wooden bridges, and environmentally conscious facilities.",
        isCanBron = false,
        service = "Biking, Nature Exploration",
        distance = 3.7,
        image = getRandImage(),
        imageLink = "https://avatars.mds.yandex.net/get-altay/9761215/2a0000018a1b4dad7cd3ab3063d0949f696b/L_height",
        isFavourite = false,
        long = 41.3128,
        lat = 69.2929,
        rating = 4.8
    ),
    PlaceDetails(
        name = "Amir Temur Square",
        address = "Tashkent, Uzbekistan",
        about = "A park centered around a statue of Amir Temur, surrounded by fountains and green spaces.",
        isCanBron = false,
        service = "Historical Landmark, Relaxation",
        distance = 1.0,
        image = getRandImage(),
        imageLink = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTQHr1pFi5A8zC6Aw2tuLmDSplxTbPELqt0g&s",
        isFavourite = true,
        long = 41.3115,
        lat = 69.2788,
        rating = 4.7
    ),
    PlaceDetails(
        name = "Independence Square",
        address = "Tashkent, Uzbekistan",
        about = "A symbolic park featuring fountains, monuments, and wide open spaces for walking.",
        isCanBron = false,
        service = "Sightseeing, Cultural Events",
        distance = 2.8,
        image = getRandImage(),
        imageLink = "https://www.tourstouzbekistan.com/uploads/2021%20photos/Tashkent/independence-square_tashkent.jpg",
        isFavourite = true,
        long = 41.3123,
        lat = 69.2787,
        rating = 4.9
    ),
    PlaceDetails(
        name = "Babur Park",
        address = "Andijan, Uzbekistan",
        about = "A park dedicated to Babur, featuring historical monuments and green relaxation areas.",
        isCanBron = false,
        service = "Historical Spot, Nature Walks",
        distance = 6.2,
        image = getRandImage(),
        imageLink = "https://uzbekistan.travel/storage/app/media/nargiza/cropped-images/Andijan1-0-0-0-0_root_ide_package_.us.smt.turizm.domen.model.getRandImage()594284202.jpg",
        isFavourite = false,
        long = 40.7821,
        lat = 72.3422,
        rating = 4.6
    )
)
val hotels = listOf(
    PlaceDetails(
        name = "Hotel Uzbekistan",
        address = "45 Mirzamakhmudov Street, Tashkent, Uzbekistan",
        about = "A historic hotel in the center of Tashkent, offering modern amenities and stunning city views.",
        isCanBron = true,
        service = "Free Wi-Fi, Restaurant, Conference Rooms",
        distance = 0.5,
        image = getRandImage(),
        imageLink = "https://hotel-uz.com/img/1de48d8162d6c82e.webp",
        isFavourite = false,
        long = 41.3123,
        lat = 69.2785,
        rating = 4.5
    ),
    PlaceDetails(
        name = "Hyatt Regency Tashkent",
        address = "Navoi Street, Tashkent, Uzbekistan",
        about = "A luxurious 5-star hotel featuring elegant rooms, a spa, and fine dining options.",
        isCanBron = true,
        service = "Swimming Pool, Spa, Business Center",
        distance = 1.2,
        image = getRandImage(),
        imageLink = "https://assets.hyatt.com/content/dam/hyatt/hyattdam/images/2017/01/31/1112/Hyatt-Regency-Tashkent-P046-Exterior-Night-View.jpg/Hyatt-Regency-Tashkent-P046-Exterior-Night-View.16x9.jpg",
        isFavourite = true,
        long = 41.3118,
        lat = 69.2795,
        rating = 4.9
    ),
    PlaceDetails(
        name = "Lotte City Hotel",
        address = "Amir Temur Street, Tashkent, Uzbekistan",
        about = "A modern hotel offering spacious rooms, excellent service, and convenient city access.",
        isCanBron = true,
        service = "Fitness Center, Room Service, Airport Shuttle",
        distance = 0.8,
        image = getRandImage(),
        imageLink = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/60661795.jpg?k=bdf2045c8fb04196308b66677504da8f33a3b0de7e439629a9769c3656a19b5a&o=&hp=1",
        isFavourite = false,
        long = 41.3134,
        lat = 69.2773,
        rating = 4.8
    ),
    PlaceDetails(
        name = "Ramada Tashkent",
        address = "Abdulla Kadiry Street, Tashkent, Uzbekistan",
        about = "A premium hotel known for its warm hospitality, business facilities, and comfortable rooms.",
        isCanBron = true,
        service = "Meeting Rooms, Free Parking, Restaurant",
        distance = 2.1,
        image = getRandImage(),
        imageLink = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/24/ff/d4/50/exterior.jpg?w=700&h=_root_ide_package_.us.smt.turizm.domen.model.getRandImage()&s=1",
        isFavourite = true,
        long = 41.3265,
        lat = 69.2911,
        rating = 4.7
    ),
    PlaceDetails(
        name = "Hilton Tashkent City",
        address = "Islam Karimov Street, Tashkent, Uzbekistan",
        about = "A luxury hotel with high-end facilities, stunning architecture, and exceptional services.",
        isCanBron = true,
        service = "Rooftop Bar, Pool, Concierge Services",
        distance = 1.7,
        image = getRandImage(),
        imageLink = "https://images.skyscrapercenter.com/building/tashkentcityzone5tower_(c)tashkent__city.jpg",
        isFavourite = false,
        long = 41.3116,
        lat = 69.2789,
        rating = 4.9
    ),
    PlaceDetails(
        name = "Le Grande Plaza Hotel",
        address = "Mustakillik Street, Tashkent, Uzbekistan",
        about = "A budget-friendly hotel offering comfortable accommodations and friendly service.",
        isCanBron = true,
        service = "Breakfast Buffet, Gym, Business Center",
        distance = 1.9,
        image = getRandImage(),
        imageLink = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/11468720.jpg?k=540b923f905b8e50b213e1b1475d16ad64a7c6969aa9f38ab079d6f3c6d53c3e&o=&hp=1",
        isFavourite = true,
        long = 41.3158,
        lat = 69.2920,
        rating = 4.3
    ),
    PlaceDetails(
        name = "Asia Bukhara Hotel",
        address = "Mekhtar Anbar Street, Bukhara, Uzbekistan",
        about = "A charming hotel with traditional Uzbek decor, located in the historic city of Bukhara.",
        isCanBron = true,
        service = "Cultural Tours, Local Cuisine, Free Wi-Fi",
        distance = 3.5,
        image = getRandImage(),
        imageLink = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/413759666.jpg?k=3b85402ed0f55d9e196698df1c6f8f840524d9f84c6d6089fe4dd9493df6c496&o=&hp=1",
        isFavourite = false,
        long = 39.7746,
        lat = 64.4285,
        rating = 4.6
    ),
    PlaceDetails(
        name = "Samarkand Plaza",
        address = "Registan Street, Samarkand, Uzbekistan",
        about = "A hotel blending traditional charm and modern amenities, ideal for exploring Samarkand.",
        isCanBron = true,
        service = "City Tours, Restaurant, Free Parking",
        distance = 4.0,
        image = getRandImage(),
        imageLink = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/517391370.jpg?k=f8e87f60b71f60752dbbd6b1c31ab4415164707f50b4a9cc56f901f1f0821d02&o=&hp=1",
        isFavourite = true,
        long = 39.6542,
        lat = 66.9741,
        rating = 4.8
    ),
    PlaceDetails(
        name = "Arba Hotel",
        address = "Gagarin Street, Samarkand, Uzbekistan",
        about = "A cozy hotel with personalized service, located near Samarkand's main attractions.",
        isCanBron = false,
        service = "Free Breakfast, Concierge, Shuttle Service",
        distance = 4.2,
        image = getRandImage(),
        imageLink = "https://oasisinternational.travel/wp-content/uploads/2020/02/Arba-hotel._root_ide_package_.us.smt.turizm.domen.model.getRandImage().jpg",
        isFavourite = false,
        long = 39.6631,
        lat = 66.9750,
        rating = 4.4
    ),
    PlaceDetails(
        name = "Grand Silk Road Hotel",
        address = "Shakhrisabz Street, Samarkand, Uzbekistan",
        about = "A boutique hotel reflecting the spirit of the Silk Road, offering exceptional dining and hospitality.",
        isCanBron = true,
        service = "Cultural Programs, Fine Dining, Gym",
        distance = 4.8,
        image = getRandImage(),
        imageLink = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/595046483.jpg?k=8c706e163e2ed3d334a76709ae7a495a016820819b552d69332dec8ed40c361f&o=&hp=1",
        isFavourite = true,
        long = 39.6681,
        lat = 66.9785,
        rating = 4.7
    )
)
val restaurants = listOf(
    PlaceDetails(
        name = "Caravan Restaurant",
        address = "Abdulla Kahhar Street, Tashkent, Uzbekistan",
        about = "A traditional Uzbek restaurant offering a cozy ambiance and a wide selection of local dishes.",
        isCanBron = true,
        service = "Traditional Uzbek Cuisine, Outdoor Seating",
        distance = 2.1,
        image = getRandImage(),
        imageLink = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT93-4ha5QpMWLkGpNGQvvBDAQW782WclmMrA&s",
        isFavourite = true,
        long = 41.3121,
        lat = 69.2875,
        rating = 4.8
    ),
    PlaceDetails(
        name = "Plov Center",
        address = "Shota Rustaveli Street, Tashkent, Uzbekistan",
        about = "A popular spot for trying Uzbekistan's national dish, plov, prepared in large traditional cauldrons.",
        isCanBron = false,
        service = "Authentic Uzbek Plov, Group Dining",
        distance = 1.8,
        image = getRandImage(),
        imageLink = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/19/f7/22/the-hall.jpg?w=1200&h=_root_ide_package_.us.smt.turizm.domen.model.getRandImage()&s=1",
        isFavourite = false,
        long = 41.3145,
        lat = 69.2968,
        rating = 4.7
    ),
    PlaceDetails(
        name = "Afsona Restaurant",
        address = "Yunusabad District, Tashkent, Uzbekistan",
        about = "A fine dining restaurant known for its blend of traditional and modern Uzbek dishes.",
        isCanBron = true,
        service = "Fine Dining, Private Events",
        distance = 3.2,
        image = getRandImage(),
        imageLink = "https://media-cdn.tripadvisor.com/media/photo-s/21/75/12/54/afsona-restaurant.jpg",
        isFavourite = true,
        long = 41.3196,
        lat = 69.2792,
        rating = 4.9
    ),
    PlaceDetails(
        name = "Silk96 Wine Bar & Restaurant",
        address = "Amir Temur Avenue, Tashkent, Uzbekistan",
        about = "A stylish restaurant offering European cuisine, a wide selection of wines, and a sophisticated atmosphere.",
        isCanBron = true,
        service = "European Cuisine, Wine Bar, Live Music",
        distance = 1.5,
        image = getRandImage(),
        imageLink = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2b/34/a7/c0/bar.jpg?w=1200&h=_root_ide_package_.us.smt.turizm.domen.model.getRandImage()&s=1",
        isFavourite = true,
        long = 41.3158,
        lat = 69.2825,
        rating = 4.6
    ),
    PlaceDetails(
        name = "Besh Qozon",
        address = "Sergeli District, Tashkent, Uzbekistan",
        about = "A family-friendly restaurant specializing in hearty Uzbek dishes, including shashlik and lagman.",
        isCanBron = false,
        service = "Family Dining, Traditional Uzbek Food",
        distance = 4.0,
        image = getRandImage(),
        imageLink = "https://irecommend.ru/sites/default/files/imagecache/copyright1/user-images/683333/QZLfyqQo5ufzgnPkwo9faA.jpg",
        isFavourite = false,
        long = 41.2800,
        lat = 69.2654,
        rating = 4.5
    ),
    PlaceDetails(
        name = "Minzifa Restaurant",
        address = "Hodja Nurobobod Street, Bukhara, Uzbekistan",
        about = "A rooftop restaurant offering spectacular views of Bukhara and a variety of local dishes.",
        isCanBron = true,
        service = "Rooftop Dining, Local Specialties",
        distance = 5.5,
        image = getRandImage(),
        imageLink = "https://media-cdn.tripadvisor.com/media/photo-s/12/a6/2e/1c/minzifa.jpg",
        isFavourite = true,
        long = 39.7758,
        lat = 64.4154,
        rating = 4.8
    ),
    PlaceDetails(
        name = "Old City Restaurant",
        address = "Registan Square, Samarkand, Uzbekistan",
        about = "A restaurant offering traditional Uzbek and Central Asian cuisine with a historical ambiance.",
        isCanBron = true,
        service = "Cultural Experience, Outdoor Dining",
        distance = 3.5,
        image = getRandImage(),
        imageLink = "https://avatars.mds.yandex.net/get-altay/2366463/2a00000170d215d7281a843a01c3966addac/orig",
        isFavourite = false,
        long = 39.6548,
        lat = 66.9747,
        rating = 4.7
    ),
    PlaceDetails(
        name = "Kishmish Restaurant",
        address = "Yakkasaray District, Tashkent, Uzbekistan",
        about = "A trendy restaurant blending modern design with traditional Uzbek flavors.",
        isCanBron = true,
        service = "Fusion Cuisine, Stylish Atmosphere",
        distance = 1.7,
        image = getRandImage(),
        imageLink = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-GZzN2pFrJ52RhZn1lQy7MCkD7humSAvr_w&s",
        isFavourite = true,
        long = 41.3127,
        lat = 69.2808,
        rating = 4.6
    ),
    PlaceDetails(
        name = "Orient Star Restaurant",
        address = "Alisher Navoi Street, Samarkand, Uzbekistan",
        about = "A restaurant known for its signature Central Asian dishes and elegant dining spaces.",
        isCanBron = true,
        service = "Signature Dishes, Private Events",
        distance = 4.1,
        image = getRandImage(),
        imageLink = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.booking.com%2Fhotel%2Fuz%2Forient-star-varaxsha.html&psig=AOvVaw1IQ8kbAlmlN_zE9nDdiAkg&ust=1732555653606000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCLDFmva-9YkDFQAAAAAdAAAAABAE",
        isFavourite = true,
        long = 39.6608,
        lat = 66.9753,
        rating = 4.7
    ),
    PlaceDetails(
        name = "Al-Chiroq Restaurant",
        address = "Furkat Street, Tashkent, Uzbekistan",
        about = "A cozy spot offering an authentic Uzbek dining experience with freshly baked bread and kebabs.",
        isCanBron = false,
        service = "Traditional Uzbek Food, Cozy Atmosphere",
        distance = 2.4,
        image = getRandImage(),
        imageLink = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYIHX2XsTaHnT5A7wWwli23KTD8pi7sUpoFg&s",
        isFavourite = false,
        long = 41.3130,
        lat = 69.2700,
        rating = 4.5
    )
)
val cafesAndFastFoods = listOf(
    PlaceDetails(
        name = "Coffee Corner",
        address = "Mirabad Street, Tashkent, Uzbekistan",
        about = "A cozy cafe known for its artisanal coffee and freshly baked pastries.",
        isCanBron = false,
        service = "Coffee, Pastries, Free Wi-Fi",
        distance = 1.2,
        image = getRandImage(),
        imageLink = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuZTeC5W1VLdeOP3SyGUXJxQjaOxtd-Nzbkw&s",
        isFavourite = true,
        long = 41.3115,
        lat = 69.2912,
        rating = 4.6
    ),
    PlaceDetails(
        name = "Starbucks Tashkent",
        address = "Amir Temur Avenue, Tashkent, Uzbekistan",
        about = "A global coffee chain offering signature drinks and snacks in a modern setting.",
        isCanBron = false,
        service = "Coffee, Snacks, Outdoor Seating",
        distance = 2.0,
        image = getRandImage(),
        imageLink = "https://api.uznews.uz/storage/uploads/posts/images/16619/main_page/4jhdSdsCFr.jpg",
        isFavourite = true,
        long = 41.3175,
        lat = 69.2818,
        rating = 4.8
    ),
    PlaceDetails(
        name = "Chaihona Lounge",
        address = "Yunusabad District, Tashkent, Uzbekistan",
        about = "A modern tea lounge offering a variety of teas and light snacks in a relaxed atmosphere.",
        isCanBron = true,
        service = "Teas, Light Meals, Hookah",
        distance = 3.5,
        image = getRandImage(),
        imageLink = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYmsLU6cik5EIpd_C4_gX0CV_6HyXTGkt74Q&s",
        isFavourite = false,
        long = 41.3164,
        lat = 69.2782,
        rating = 4.7
    ),
    PlaceDetails(
        name = "Burger Lab",
        address = "Shota Rustaveli Street, Tashkent, Uzbekistan",
        about = "A fast-food joint offering gourmet burgers and unique flavor combinations.",
        isCanBron = false,
        service = "Burgers, Fast Food, Takeaway",
        distance = 1.6,
        image = getRandImage(),
        imageLink = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQK_rkuCQBP4ZtpJhwwOVyglUx--tCyuwcEFw&s",
        isFavourite = true,
        long = 41.3142,
        lat = 69.2951,
        rating = 4.5
    ),
    PlaceDetails(
        name = "McDonald's Tashkent",
        address = "Sergeli District, Tashkent, Uzbekistan",
        about = "A branch of the popular fast-food chain offering classic burgers, fries, and shakes.",
        isCanBron = false,
        service = "Fast Food, Family Dining, Drive-Thru",
        distance = 2.8,
        image = getRandImage(),
        imageLink = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUstiqK3-KiUs_47vjAY8yalRlFK9OR17Nxw&s",
        isFavourite = false,
        long = 41.3050,
        lat = 69.2704,
        rating = 4.6
    ),
    PlaceDetails(
        name = "Caffeine Coffee Shop",
        address = "Broadway, Tashkent, Uzbekistan",
        about = "A trendy coffee shop known for its cold brews, lattes, and laid-back vibe.",
        isCanBron = true,
        service = "Coffee, Desserts, Chill Atmosphere",
        distance = 1.1,
        image = getRandImage(),
        imageLink = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/63/a7/61/renewed-coffee-shop-in.jpg?w=1200&h=_root_ide_package_.us.smt.turizm.domen.model.getRandImage()&s=1",
        isFavourite = true,
        long = 41.3152,
        lat = 69.2828,
        rating = 4.7
    ),
    PlaceDetails(
        name = "KFC Tashkent",
        address = "Mustakillik Avenue, Tashkent, Uzbekistan",
        about = "A branch of the global fast-food chain specializing in fried chicken.",
        isCanBron = false,
        service = "Fast Food, Family Dining, Delivery",
        distance = 2.3,
        image = getRandImage(),
        imageLink = "https://avatars.mds.yandex.net/get-altay/5234013/2a00000186d04394bbf6dcd95e73fec4e6f3/L_height",
        isFavourite = true,
        long = 41.3139,
        lat = 69.2881,
        rating = 4.4
    ),
    PlaceDetails(
        name = "Gloria Jean's Coffees",
        address = "Registan Square, Samarkand, Uzbekistan",
        about = "A cozy cafe offering a variety of coffee blends, cakes, and quick bites.",
        isCanBron = false,
        service = "Coffee, Desserts, Quick Bites",
        distance = 4.0,
        image = getRandImage(),
        imageLink = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTao9pmtu2z1F-FelEs8ucY3_d07BTDq0UULw&s",
        isFavourite = false,
        long = 39.6545,
        lat = 66.9750,
        rating = 4.5
    ),
    PlaceDetails(
        name = "Tim's Coffee",
        address = "Hodja Nurobobod Street, Bukhara, Uzbekistan",
        about = "A small coffee shop offering a mix of local and international coffee drinks.",
        isCanBron = false,
        service = "Coffee, Local Pastries, Free Wi-Fi",
        distance = 5.1,
        image = getRandImage(),
        imageLink = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLObXEEOiiBiBdaLdJkj-GObT7C_mjNY8SNw&s",
        isFavourite = true,
        long = 39.7754,
        lat = 64.4162,
        rating = 4.6
    ),
    PlaceDetails(
        name = "Pizza Hut Samarkand",
        address = "Gagarin Street, Samarkand, Uzbekistan",
        about = "A fast-food chain offering pizza, pasta, and other Italian-American classics.",
        isCanBron = true,
        service = "Pizza, Fast Food, Takeaway",
        distance = 3.9,
        image = getRandImage(),
        imageLink = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2d/4c/9c/e2/caption.jpg?w=600&h=600&s=1",
        isFavourite = false,
        long = 39.6610,
        lat = 66.9763,
        rating = 4.5
    )
)


fun getEmptyData(
    id: String? = null,
    name: String? = null,
    address: String? = null,
    distance: Double? = null,
    about: String? = null,
    service: String? = null,
    isCanBron: Boolean? = null,
    isFavourite: Boolean? = null,
    long: Double? = null,
    lat: Double? = null,
    rating: Double? = null,
    image: Int? = null,
    imageLink: String? = null
): PlaceDetails = PlaceDetails(
    name = name ?: "",
    about = about ?: "",
    address = address ?: "",
    distance = distance ?: 0.0,
    image = image?:-1,
    imageLink = imageLink,
    long = long ?: 0.0,
    lat = lat ?: 0.0,
    rating = rating ?: 0.0,
    service = service ?: "",
    isFavourite = isFavourite ?: false,
    isCanBron = isCanBron ?: false
)
